name: Daily CSV Update

on:
  schedule:
    - cron: '30 17 * * *'  # Runs daily at 1:00 PDT
  workflow_dispatch:       # Allows manual trigger

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # 🔧 updated version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        run: python create_tables.py

      - name: Commit updated CSV files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add daily_player_stats_wide.csv daily_team_combined_stats.csv
          git commit -m "Daily CSV updates: $(date -u +'%Y-%m-%d %H:%M:%S')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
